#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
# edit config file
server_config=\
"
frontend my_frontend
        bind *:80
        mode http
        default_backend my_servers
backend my_servers
	mode http
        balance roundrobin
        server 526893-web-01 100.26.246.127:80 check
        server 526893-web-02 3.94.211.197:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the haproxy service
sudo service haproxy restart
