#!/usr/bin/env bash
# same as task 0 but stops process id of nginx

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

#restart nginx
sudo service nginx restart

#stops processid of nginx
rm /run/nginx.pid
